import type {
  CampaignRecord,
  DeliverableRecord,
  MountainExternalTargetRecord,
  MountainMembershipRecord,
  MountainRecord,
  ReplanRecord,
  RewardSplitRecord,
  SwarmSessionRecord,
  VerificationRunRecord,
  WorkLeaseRecord,
  WorkSpecRecord,
} from "./types";

const FIXTURE_NOW = new Date("2026-03-09T09:00:00.000Z");

function iso(offsetHours: number) {
  return new Date(FIXTURE_NOW.getTime() + offsetHours * 60 * 60 * 1000).toISOString();
}

export const METACULUS_SUMMIT_SLUG = "metaculus-spring-aib-2026";
export const METACULUS_SUMMIT_ID = "mountain-metaculus-spring-aib-2026";
export const METACULUS_OFFICIAL_AGENT_NAME = "metaculus-official-bot";
export const PLACEHOLDER_MOUNTAIN_SLUGS = ["riemann-frontier", "crispr-alignment-map"] as const;

export const metaculusMountainSeed: Omit<MountainRecord, "created_at" | "updated_at"> = {
  id: METACULUS_SUMMIT_ID,
  slug: METACULUS_SUMMIT_SLUG,
  title: "Metaculus Spring AIB 2026 Forecast Engine",
  thesis:
    "Fund a supervisor-governed forecasting swarm that researches, calibrates, writes rationale, and submits one official autonomous Metaculus competition bot.",
  target_problem:
    "Win the Metaculus Spring AI Benchmark 2026 with a fully compliant autonomous forecasting system.",
  success_criteria:
    "Finish first in the official competition while maintaining no-human-in-the-loop operation, reasoning comments for every scored forecast, and a reproducible disclosure package.",
  domain: "forecasting",
  horizon: "Spring 2026 season + postmortem",
  visibility: "public",
  status: "active",
  created_by_account_id: "admin-seed",
  total_budget_credits: 400000,
  budget_envelopes: {
    decomposition: 40000,
    execution: 180000,
    replication: 70000,
    synthesis: 50000,
    emergency: 60000,
  },
  governance_policy: {
    noHumanInLoopDuringForecasting: true,
    mandatoryForecastComments: true,
    singlePrizeEligibleEntry: true,
    disclosureRequired: true,
    externalProvider: "metaculus",
  },
  decomposition_policy: {
    maxBranchDepth: 5,
    preferredRoleMix: [
      "researcher",
      "retriever",
      "forecaster",
      "calibrator",
      "comment_writer",
      "red_team",
      "submission_operator",
    ],
    requireCapabilityRouting: true,
  },
  settlement_policy_mode: "dynamic_difficulty",
  settlement_policy: {
    replicationBonus: 1.2,
    contradictionResolutionBonus: 1.3,
    calibrationBonus: 1.25,
    officialSubmissionBonus: 1.15,
  },
  tags: ["metaculus", "forecasting", "autonomy", "calibration", "competition"],
  metadata: {
    season: "spring-aib-2026",
    current_season: "Spring 2026",
    question_coverage: 0,
    forecast_count: 0,
    comment_compliance_rate: 0,
    leaderboard_status: "not_started",
    last_sync_at: null,
  },
  launched_at: iso(-72),
  completed_at: null,
};

export const metaculusCampaignSeeds: Array<
  Omit<CampaignRecord, "created_at" | "updated_at" | "owner_account_id">
> = [
  {
    id: "campaign-metaculus-rules",
    mountain_id: METACULUS_SUMMIT_ID,
    title: "Rules + Compliance Mirror",
    summary:
      "Capture tournament rules, comment obligations, disclosure expectations, and no-human-in-loop policy as machine-checkable operating constraints.",
    hypothesis:
      "The highest-leverage early investment is making rule violations structurally difficult rather than relying on operator memory.",
    status: "active",
    risk_ceiling: "high",
    decomposition_aggressiveness: 82,
    replication_policy: { minIndependentReplications: 1 },
    governance_policy: { requireHumanReviewForRuleSnapshot: true },
    budget_credits: 28000,
    milestone_order: 1,
  },
  {
    id: "campaign-metaculus-intake",
    mountain_id: METACULUS_SUMMIT_ID,
    title: "Question Intake + Prioritization",
    summary:
      "Ingest questions, classify them, track deadlines, and keep the official forecasting queue prioritized for coverage and timing.",
    hypothesis:
      "Coverage and timeliness are a competitive edge only if the queue is normalized fast enough to avoid late low-information forecasts.",
    status: "active",
    risk_ceiling: "medium",
    decomposition_aggressiveness: 74,
    replication_policy: { minIndependentReplications: 1 },
    governance_policy: { requireQuestionCanonicalization: true },
    budget_credits: 42000,
    milestone_order: 2,
  },
  {
    id: "campaign-metaculus-research",
    mountain_id: METACULUS_SUMMIT_ID,
    title: "Research + Evidence Retrieval",
    summary:
      "Collect sources, summarize evidence, and build reusable question-specific knowledge packs.",
    hypothesis:
      "Evidence quality and refresh cadence are more decisive than prompt cleverness on most questions.",
    status: "active",
    risk_ceiling: "medium",
    decomposition_aggressiveness: 76,
    replication_policy: { minIndependentReplications: 2 },
    governance_policy: { requireSourceLineage: true },
    budget_credits: 76000,
    milestone_order: 3,
  },
  {
    id: "campaign-metaculus-forecasting",
    mountain_id: METACULUS_SUMMIT_ID,
    title: "Forecast Generation + Calibration",
    summary:
      "Generate probabilistic forecasts, ensemble competing lines, and continuously recalibrate confidence.",
    hypothesis:
      "Calibration discipline and meta-modeling beat single-pass forecast generation.",
    status: "active",
    risk_ceiling: "high",
    decomposition_aggressiveness: 88,
    replication_policy: { minIndependentReplications: 2 },
    governance_policy: { requireBacktestDeltas: true },
    budget_credits: 108000,
    milestone_order: 4,
  },
  {
    id: "campaign-metaculus-comments",
    mountain_id: METACULUS_SUMMIT_ID,
    title: "Comment Writer + Rationale QA",
    summary:
      "Produce the required public reasoning comment for every scored forecast and verify that it is coherent, compliant, and aligned with the probability output.",
    hypothesis:
      "Comment quality is both a tournament requirement and a debugging surface for model reasoning.",
    status: "active",
    risk_ceiling: "medium",
    decomposition_aggressiveness: 71,
    replication_policy: { minIndependentReplications: 1 },
    governance_policy: { requireCommentTemplateChecks: true },
    budget_credits: 46000,
    milestone_order: 5,
  },
  {
    id: "campaign-metaculus-submission",
    mountain_id: METACULUS_SUMMIT_ID,
    title: "Official Submission Pipeline",
    summary:
      "Run one official outward-facing agent that posts forecasts and comments to the tournament while preserving full auditability.",
    hypothesis:
      "A single tightly-governed submission path reduces prize-eligibility and operational risk more than it costs in experimentation speed.",
    status: "active",
    risk_ceiling: "high",
    decomposition_aggressiveness: 62,
    replication_policy: { minIndependentReplications: 1 },
    governance_policy: { requireSingleOfficialAgent: true },
    budget_credits: 36000,
    milestone_order: 6,
  },
  {
    id: "campaign-metaculus-backtesting",
    mountain_id: METACULUS_SUMMIT_ID,
    title: "Backtesting + Leaderboard Intelligence",
    summary:
      "Track scoring, ablations, rank movement, and recurrent error modes across the season.",
    hypothesis:
      "Fast feedback on calibration and timing errors compounds into a stronger bot over the season.",
    status: "active",
    risk_ceiling: "medium",
    decomposition_aggressiveness: 64,
    replication_policy: { minIndependentReplications: 1 },
    governance_policy: { requireScoreAuditTrail: true },
    budget_credits: 36000,
    milestone_order: 7,
  },
  {
    id: "campaign-metaculus-redteam",
    mountain_id: METACULUS_SUMMIT_ID,
    title: "Red-Team + Reliability",
    summary:
      "Probe rule violations, stale data, prompt regressions, submission failures, and drift before they harm the official bot.",
    hypothesis:
      "Competition systems fail more often from operational fragility than from lack of modeling sophistication.",
    status: "active",
    risk_ceiling: "high",
    decomposition_aggressiveness: 79,
    replication_policy: { minIndependentReplications: 1 },
    governance_policy: { requireEscalationOnBotFailure: true },
    budget_credits: 28000,
    milestone_order: 8,
  },
];

export const metaculusWorkSpecSeeds: Array<
  Omit<WorkSpecRecord, "created_at" | "updated_at" | "owner_account_id">
> = [
  {
    id: "spec-metaculus-rules-ingestion",
    mountain_id: METACULUS_SUMMIT_ID,
    campaign_id: "campaign-metaculus-rules",
    parent_work_spec_id: null,
    title: "Build the competition compliance matrix",
    summary:
      "Convert the tournament rules into structured constraints covering single-entry policy, autonomous operation, comment obligations, and disclosure requirements.",
    status: "ready",
    contribution_type: "governance",
    role_type: "reviewer",
    allowed_role_types: ["reviewer", "verifier", "synthesizer"],
    input_contract: { requiredArtifacts: ["tournament rules", "resources docs"] },
    output_contract: { requiredDeliverables: ["compliance matrix", "policy checks"] },
    verification_contract: { requireHumanApproval: true },
    dependency_edges: [],
    reward_envelope: { baseCredits: 6500 },
    checkpoint_cadence_minutes: 180,
    duplication_policy: { allowRedundantVerification: true },
    risk_class: "high",
    priority: 100,
    speculative: false,
    synthesis_required: true,
    metadata: {
      summitSeed: true,
      assignmentRationale: "Locks the legal and operational rails for the entire program.",
    },
  },
  {
    id: "spec-metaculus-question-intake",
    mountain_id: METACULUS_SUMMIT_ID,
    campaign_id: "campaign-metaculus-intake",
    parent_work_spec_id: null,
    title: "Normalize question intake and backlog priority",
    summary:
      "Ingest tournament questions, normalize identifiers/deadlines, classify domains, and maintain a ranked backlog for the official bot.",
    status: "ready",
    contribution_type: "operations",
    role_type: "executor",
    allowed_role_types: ["executor", "synthesizer"],
    input_contract: { requiredArtifacts: ["question feed", "deadline metadata"] },
    output_contract: { requiredDeliverables: ["normalized backlog", "priority rubric"] },
    verification_contract: { requireDeadlineChecks: true },
    dependency_edges: [],
    reward_envelope: { baseCredits: 7200 },
    checkpoint_cadence_minutes: 120,
    duplication_policy: { duplicateOnContradiction: true },
    risk_class: "moderate",
    priority: 96,
    speculative: false,
    synthesis_required: false,
    metadata: {
      summitSeed: true,
      assignmentRationale: "Coverage and timing both depend on a clean intake rail.",
    },
  },
  {
    id: "spec-metaculus-research-packs",
    mountain_id: METACULUS_SUMMIT_ID,
    campaign_id: "campaign-metaculus-research",
    parent_work_spec_id: null,
    title: "Generate evidence packs for active questions",
    summary:
      "Retrieve and summarize evidence into reusable structured packets for forecasters and comment writers.",
    status: "ready",
    contribution_type: "research",
    role_type: "executor",
    allowed_role_types: ["executor", "reviewer", "synthesizer"],
    input_contract: { requiredArtifacts: ["normalized backlog"] },
    output_contract: { requiredDeliverables: ["evidence pack", "source map"] },
    verification_contract: { requireSourceLineage: true },
    dependency_edges: [{ work_spec_id: "spec-metaculus-question-intake", dependency_kind: "blocks" }],
    reward_envelope: { baseCredits: 8800 },
    checkpoint_cadence_minutes: 150,
    duplication_policy: { allowRedundantVerification: true },
    risk_class: "moderate",
    priority: 94,
    speculative: false,
    synthesis_required: false,
    metadata: {
      summitSeed: true,
      assignmentRationale: "Evidence quality is the main upstream driver of forecast quality.",
    },
  },
  {
    id: "spec-metaculus-baseline-forecaster",
    mountain_id: METACULUS_SUMMIT_ID,
    campaign_id: "campaign-metaculus-forecasting",
    parent_work_spec_id: null,
    title: "Run the baseline forecast generator",
    summary:
      "Produce calibrated probability estimates from active evidence packs and record uncertainty decomposition for later ensembling.",
    status: "ready",
    contribution_type: "forecasting",
    role_type: "executor",
    allowed_role_types: ["executor", "synthesizer"],
    input_contract: { requiredArtifacts: ["evidence pack", "question metadata"] },
    output_contract: { requiredDeliverables: ["probability draft", "calibration notes"] },
    verification_contract: { requireBacktestScore: true },
    dependency_edges: [{ work_spec_id: "spec-metaculus-research-packs", dependency_kind: "blocks" }],
    reward_envelope: { baseCredits: 12000 },
    checkpoint_cadence_minutes: 120,
    duplication_policy: { duplicateOnContradiction: true },
    risk_class: "high",
    priority: 98,
    speculative: false,
    synthesis_required: true,
    metadata: {
      summitSeed: true,
      assignmentRationale: "This is the core forecasting engine the rest of the system scaffolds.",
    },
  },
  {
    id: "spec-metaculus-ensemble-calibration",
    mountain_id: METACULUS_SUMMIT_ID,
    campaign_id: "campaign-metaculus-forecasting",
    parent_work_spec_id: "spec-metaculus-baseline-forecaster",
    title: "Calibrate and ensemble competing forecast lines",
    summary:
      "Combine multiple forecast proposals, measure calibration drift, and pick the submission candidate for the official bot.",
    status: "queued",
    contribution_type: "synthesis",
    role_type: "synthesizer",
    allowed_role_types: ["synthesizer", "verifier"],
    input_contract: { requiredArtifacts: ["probability drafts", "historical performance"] },
    output_contract: { requiredDeliverables: ["ensemble candidate", "calibration report"] },
    verification_contract: { requireHistoricalComparison: true },
    dependency_edges: [{ work_spec_id: "spec-metaculus-baseline-forecaster", dependency_kind: "blocks" }],
    reward_envelope: { baseCredits: 11000 },
    checkpoint_cadence_minutes: 180,
    duplication_policy: { allowRedundantVerification: true },
    risk_class: "high",
    priority: 92,
    speculative: true,
    synthesis_required: false,
    metadata: {
      summitSeed: true,
      assignmentRationale: "Calibration and meta-selection should be explicit, not implicit prompt behavior.",
    },
  },
  {
    id: "spec-metaculus-comment-writer",
    mountain_id: METACULUS_SUMMIT_ID,
    campaign_id: "campaign-metaculus-comments",
    parent_work_spec_id: null,
    title: "Generate mandatory rationale comments",
    summary:
      "Draft the public reasoning comment required for every scored forecast and validate it against the probability output and evidence pack.",
    status: "ready",
    contribution_type: "communication",
    role_type: "executor",
    allowed_role_types: ["executor", "reviewer", "synthesizer"],
    input_contract: { requiredArtifacts: ["ensemble candidate", "evidence pack"] },
    output_contract: { requiredDeliverables: ["forecast comment", "comment QA"] },
    verification_contract: { requireCommentPresence: true },
    dependency_edges: [{ work_spec_id: "spec-metaculus-ensemble-calibration", dependency_kind: "blocks" }],
    reward_envelope: { baseCredits: 7600 },
    checkpoint_cadence_minutes: 120,
    duplication_policy: { duplicateOnContradiction: true },
    risk_class: "moderate",
    priority: 95,
    speculative: false,
    synthesis_required: false,
    metadata: {
      summitSeed: true,
      assignmentRationale: "Tournament compliance depends on this comment rail being reliable.",
    },
  },
  {
    id: "spec-metaculus-official-submission",
    mountain_id: METACULUS_SUMMIT_ID,
    campaign_id: "campaign-metaculus-submission",
    parent_work_spec_id: null,
    title: "Operate the official submission bot",
    summary:
      "Submit the selected forecast and required comment through one outward-facing bot while recording an audit trail for every action.",
    status: "queued",
    contribution_type: "operations",
    role_type: "executor",
    allowed_role_types: ["executor"],
    input_contract: { requiredArtifacts: ["ensemble candidate", "forecast comment", "question identifier"] },
    output_contract: { requiredDeliverables: ["submission receipt", "audit log"] },
    verification_contract: { requireSubmissionReceipt: true },
    dependency_edges: [
      { work_spec_id: "spec-metaculus-ensemble-calibration", dependency_kind: "blocks" },
      { work_spec_id: "spec-metaculus-comment-writer", dependency_kind: "blocks" },
    ],
    reward_envelope: { baseCredits: 9000, officialSubmissionBonus: 1.15 },
    checkpoint_cadence_minutes: 60,
    duplication_policy: { singleOfficialActor: true },
    risk_class: "high",
    priority: 99,
    speculative: false,
    synthesis_required: false,
    metadata: {
      summitSeed: true,
      assignmentRationale: "Prize eligibility depends on one official outward-facing bot path.",
    },
  },
  {
    id: "spec-metaculus-backtest",
    mountain_id: METACULUS_SUMMIT_ID,
    campaign_id: "campaign-metaculus-backtesting",
    parent_work_spec_id: null,
    title: "Score backtests and leaderboard deltas",
    summary:
      "Track performance over time, measure the cost of late forecasts, and surface regressions for the supervisor.",
    status: "ready",
    contribution_type: "evaluation",
    role_type: "verifier",
    allowed_role_types: ["verifier", "synthesizer"],
    input_contract: { requiredArtifacts: ["submission log", "historical questions"] },
    output_contract: { requiredDeliverables: ["score report", "leaderboard delta brief"] },
    verification_contract: { requireHistoricalReplay: true },
    dependency_edges: [{ work_spec_id: "spec-metaculus-official-submission", dependency_kind: "supports" }],
    reward_envelope: { baseCredits: 8400 },
    checkpoint_cadence_minutes: 240,
    duplication_policy: { allowRedundantVerification: true },
    risk_class: "moderate",
    priority: 84,
    speculative: false,
    synthesis_required: false,
    metadata: {
      summitSeed: true,
      assignmentRationale: "The supervisor needs hard feedback to re-route work.",
    },
  },
  {
    id: "spec-metaculus-redteam",
    mountain_id: METACULUS_SUMMIT_ID,
    campaign_id: "campaign-metaculus-redteam",
    parent_work_spec_id: null,
    title: "Probe reliability and rule-failure scenarios",
    summary:
      "Continuously test stale queues, missing comments, prompt drift, and failed submission branches before they affect the official bot.",
    status: "ready",
    contribution_type: "verification",
    role_type: "verifier",
    allowed_role_types: ["verifier", "reviewer"],
    input_contract: { requiredArtifacts: ["submission pipeline", "compliance matrix"] },
    output_contract: { requiredDeliverables: ["failure report", "escalation bundle"] },
    verification_contract: { requireEscalationOnFailure: true },
    dependency_edges: [
      { work_spec_id: "spec-metaculus-rules-ingestion", dependency_kind: "blocks" },
      { work_spec_id: "spec-metaculus-official-submission", dependency_kind: "supports" },
    ],
    reward_envelope: { baseCredits: 7800, contradictionResolutionBonus: 1.3 },
    checkpoint_cadence_minutes: 180,
    duplication_policy: { allowRedundantVerification: true },
    risk_class: "high",
    priority: 90,
    speculative: true,
    synthesis_required: false,
    metadata: {
      summitSeed: true,
      assignmentRationale: "Production failures need to be discovered before the competition sees them.",
    },
  },
];

export function buildFixtureRecords() {
  const mountain: MountainRecord = {
    ...metaculusMountainSeed,
    created_at: iso(-96),
    updated_at: iso(-1),
  };

  const campaigns: CampaignRecord[] = metaculusCampaignSeeds.map((campaign, index) => ({
    ...campaign,
    owner_account_id: "admin-seed",
    created_at: iso(-90 + index),
    updated_at: iso(-3 + index * 0.1),
  }));

  const workSpecs: WorkSpecRecord[] = metaculusWorkSpecSeeds.map((spec, index) => ({
    ...spec,
    owner_account_id: "admin-seed",
    created_at: iso(-72 + index),
    updated_at: iso(-2 + index * 0.05),
  }));

  const workLeases: WorkLeaseRecord[] = [
    {
      id: "lease-metaculus-rules",
      mountain_id: METACULUS_SUMMIT_ID,
      campaign_id: "campaign-metaculus-rules",
      work_spec_id: "spec-metaculus-rules-ingestion",
      assigned_agent_id: "demo-agent",
      assigned_by_account_id: "admin-seed",
      status: "active",
      offered_at: iso(-18),
      accepted_at: iso(-17.5),
      started_at: iso(-17),
      expires_at: iso(24),
      checkpoint_due_at: iso(2),
      submitted_at: null,
      verified_at: null,
      renewal_count: 1,
      failure_reason: null,
      rationale: "This agent has the best governance and synthesis score on compliance-heavy work.",
      lease_token_hash: null,
      checkpoint_payload: {
        progress: "Rules matrix drafted; pending disclosure cross-check.",
        evidence: ["tournament rules snapshot", "resources notes"],
        blockers: [],
      },
      metadata: {
        whyAssigned: "High review quality and strong compliance fit.",
      },
      created_at: iso(-18),
      updated_at: iso(-1),
    },
  ];

  const swarmSessions: SwarmSessionRecord[] = [
    {
      id: "swarm-metaculus-calibration",
      mountain_id: METACULUS_SUMMIT_ID,
      campaign_id: "campaign-metaculus-forecasting",
      work_spec_id: "spec-metaculus-ensemble-calibration",
      title: "Calibration cell",
      objective: "Pair forecasters, calibrators, and verification specialists around the season’s highest-value questions.",
      status: "forming",
      coalition_terms: { maxMembers: 5, requireQuestionAuditTrail: true },
      credit_split_policy: { proposer: 0.1, executor: 0.45, verifier: 0.3, synthesizer: 0.15 },
      coordination_context: { room: "campaign-metaculus-forecasting", inviteReason: "Need one calibration verifier." },
      created_by_agent_id: "agent-synth",
      created_at: iso(-8),
      updated_at: iso(-1),
    },
  ];

  const deliverables: DeliverableRecord[] = [
    {
      id: "deliverable-metaculus-rules",
      mountain_id: METACULUS_SUMMIT_ID,
      campaign_id: "campaign-metaculus-rules",
      work_spec_id: "spec-metaculus-rules-ingestion",
      work_lease_id: "lease-metaculus-rules",
      agent_id: "demo-agent",
      deliverable_type: "report",
      title: "Competition compliance matrix v0",
      summary: "Structured rule snapshot covering bot eligibility, comment obligations, and disclosure expectations.",
      evidence_bundle: [{ kind: "rules_page", provider: "metaculus" }],
      claims: [{ statement: "Every scored forecast must publish a rationale comment." }],
      references_bundle: [{ source: "Metaculus Spring AI Benchmark 2026" }],
      upstream_refs: [],
      confidence: 82,
      novelty_score: 48,
      reproducibility_score: 88,
      artifact_url: null,
      metadata: { public_safe: true },
      created_at: iso(-6),
      updated_at: iso(-2),
    },
  ];

  const verificationRuns: VerificationRunRecord[] = [
    {
      id: "verification-metaculus-rules",
      mountain_id: METACULUS_SUMMIT_ID,
      campaign_id: "campaign-metaculus-rules",
      work_spec_id: "spec-metaculus-rules-ingestion",
      deliverable_id: "deliverable-metaculus-rules",
      verifier_agent_id: "agent-verifier",
      requested_by_agent_id: "demo-agent",
      verification_type: "rules-audit",
      outcome: "needs_replication",
      confidence_delta: 6,
      contradiction_count: 0,
      findings: [{ statement: "Need explicit handling for disclosure and source reuse policy." }],
      evidence_bundle: [{ kind: "secondary_review" }],
      requested_at: iso(-5),
      completed_at: null,
      created_at: iso(-5),
      updated_at: iso(-1),
    },
  ];

  const replans: ReplanRecord[] = [
    {
      id: "replan-metaculus-disclosure",
      mountain_id: METACULUS_SUMMIT_ID,
      campaign_id: "campaign-metaculus-rules",
      work_spec_id: "spec-metaculus-rules-ingestion",
      work_lease_id: "lease-metaculus-rules",
      issued_by_account_id: "admin-seed",
      reason: "manual_intervention",
      action: "Split disclosure rules into a dedicated verification branch.",
      summary: "The compliance matrix needs a stronger disclosure and code-release branch before official launch.",
      status: "open",
      payload: { target_type: "work_spec" },
      created_at: iso(-4),
      updated_at: iso(-1),
    },
  ];

  const rewardSplits: RewardSplitRecord[] = [
    {
      id: "reward-metaculus-rules",
      mountain_id: METACULUS_SUMMIT_ID,
      campaign_id: "campaign-metaculus-rules",
      work_spec_id: "spec-metaculus-rules-ingestion",
      work_lease_id: "lease-metaculus-rules",
      deliverable_id: "deliverable-metaculus-rules",
      beneficiary_agent_id: "demo-agent",
      beneficiary_account_id: null,
      role: "reviewer",
      amount_credits: 1800,
      rationale: "Initial compliance matrix delivered and accepted for follow-on refinement.",
      settlement_status: "pending",
      metadata: {},
      created_at: iso(-3),
      updated_at: iso(-1),
    },
  ];

  const memberships: MountainMembershipRecord[] = [
    {
      id: "membership-metaculus-admin",
      mountain_id: METACULUS_SUMMIT_ID,
      account_id: "admin-seed",
      agent_id: null,
      role: "operator",
      status: "active",
      metadata: {},
      created_at: iso(-96),
      updated_at: iso(-96),
    },
    {
      id: "membership-metaculus-official-bot",
      mountain_id: METACULUS_SUMMIT_ID,
      account_id: null,
      agent_id: "official-agent-seed",
      role: "official_bot",
      status: "active",
      metadata: {},
      created_at: iso(-72),
      updated_at: iso(-72),
    },
  ];

  const externalTargets: MountainExternalTargetRecord[] = [
    {
      id: "target-metaculus-spring-aib-2026",
      mountain_id: METACULUS_SUMMIT_ID,
      provider: "metaculus",
      target_slug: "spring-aib-2026",
      official_agent_id: "official-agent-seed",
      rules_snapshot: {
        noHumanInLoopDuringForecasting: true,
        mandatoryCommentPerForecast: true,
        singlePrizeEligibleBotPerUser: true,
        disclosureRequired: true,
      },
      submission_policy: {
        outwardFacingMode: "single_official_bot",
        officialSubmissionWorker: "spec-metaculus-official-submission",
      },
      disclosure_policy: {
        publishMethodSummary: true,
        preservePromptAuditTrail: true,
      },
      metadata: {
        current_season: "Spring 2026",
        question_coverage: 0,
        forecast_count: 0,
        comment_compliance_rate: 0,
        leaderboard_status: "not_started",
        last_sync_at: null,
      },
      created_at: iso(-96),
      updated_at: iso(-1),
    },
  ];

  return {
    mountains: [mountain],
    campaigns,
    workSpecs,
    workLeases,
    swarmSessions,
    deliverables,
    verificationRuns,
    replans,
    rewardSplits,
    memberships,
    externalTargets,
  };
}
